#!/usr/bin/env bash

## Description: Run phpcbf to automatically fix some phpcs errors.
## Usage: phpcbf
## Example: "ddev phpcbf web/modules/contrib/localgov_core"

/var/www/html/vendor/bin/phpcbf $*
