name: Test LocalGov Drupal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Extract Git branch name outside of a pull request
        if: github.event_name != 'pull_request'
        run: echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Or extract Git branch name from a pull request
        if: github.event_name == 'pull_request'
        run: echo "GIT_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Create LocalGov Drupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project:dev-${GIT_BRANCH} html

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
